name: AppXplorerDemo
options:
  bundleIdPrefix: com.appxplorer
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

packages:
  AppXplorerServer:
    path: ../server

targets:
  AppXplorerDemo:
    type: application
    platform: iOS
    sources:
      - AppXplorerDemo
    dependencies:
      - package: AppXplorerServer
      - package: AppXplorerServer
        product: AppXplorerIroh
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.appxplorer.demo
        INFOPLIST_FILE: AppXplorerDemo/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
